spring:
  application:
          name: simple-project-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/ogcsManager
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  security:
    user:
      name: user
      password: password
  sql:
    init:
      mode: always
